appVersion: apps/01
kind: Deployment 
metadata:
   name: bankapp-deployment
spec:
   replicas: 2
   template:
    metadata:
	  labels:
	  app: bankapp-deployment
	containers:
	- name:  bankapp-deployment
	  image: daksha25/bankapp:01
	  ports:
	  - containerPort: 8080

 
